module.exports.updateKasutaja = "UPDATE Kasutaja SET kasutaja_seisu_id = ?, kasutaja_staatuse_id = ?, eesnimi = ?, perenimi = ?, volg = ?, admin_on_kinnitanud = ? WHERE kasutaja_id = ?";
module.exports.updateToode = "UPDATE Toode SET toote_kategooria_id = ?, toote_nimetus = ?, hetke_kogus = ?, myygi_hind = ?, oma_hind = ? WHERE toote_id = ?";
module.exports.insertToode = "INSERT INTO Toode (toote_kategooria_id, toote_nimetus, hetke_kogus, myygi_hind, oma_hind) VALUES (?, ?, ?, ?, ?)";
module.exports.deleteKasutajaID = "DELETE FROM Kasutaja WHERE kasutaja_id = ?";
module.exports.deleteToodeID = "DELETE FROM Toode WHERE toote_id = ?";
module.exports.insertTooteMuutus = "INSERT INTO Toote_Koguse_Muutus (toote_nimi, kogus, tegevus) VALUES (?, ?, ?)";
module.exports.insertKasutajaMuutus = "INSERT INTO Kasutaja_Muutus (kasutaja_nimi, tegevus, muudeti) VALUES (?, ?, ?)";
module.exports.kasutajaNimiID = "SELECT staatuse_nimetus, eesnimi, perenimi FROM Kasutaja INNER JOIN Kasutaja_Staatus ON Kasutaja.kasutaja_staatuse_id = Kasutaja_Staatus.kasutaja_staatuse_id WHERE kasutaja_id = ?";
module.exports.staatusNimetusID = "SELECT staatuse_nimetus FROM Kasutaja_Staatus WHERE kasutaja_staatuse_id = ?";
module.exports.tooteNimetusID = "SELECT toote_nimetus, hetke_kogus FROM Toode WHERE toote_id = ?";
module.exports.topOstjad = "SELECT staatuse_nimetus, eesnimi, perenimi, volg FROM Kasutaja INNER JOIN Kasutaja_Staatus ON Kasutaja.kasutaja_staatuse_id = Kasutaja_Staatus.kasutaja_staatuse_id ORDER BY volg DESC LIMIT 10";
module.exports.topTooted = "SELECT toote_nimi, COUNT(toote_nimi) AS arv FROM Ost WHERE aeg BETWEEN DATE_SUB(NOW(), INTERVAL 90 DAY) AND NOW() GROUP BY toote_nimi ORDER BY COUNT(toote_nimi) DESC, toote_nimi LIMIT 10";
module.exports.kasutajad = "SELECT kasutaja_id, eesnimi, perenimi, volg, coetus, admin_on_kinnitanud, staatuse_nimetus AS staatus, seisu_nimetus AS seisuNim FROM Kasutaja INNER JOIN Kasutaja_Seis ON Kasutaja.kasutaja_seisu_id = Kasutaja_Seis.kasutaja_seisu_id INNER JOIN Kasutaja_Staatus ON Kasutaja.kasutaja_staatuse_id = Kasutaja_Staatus.kasutaja_staatuse_id ORDER BY coetus DESC, staatus, eesnimi, perenimi";
module.exports.kasutajaID = "SELECT * FROM Kasutaja WHERE kasutaja_id =?";
module.exports.toodeID = "SELECT * FROM (Toode INNER JOIN Toote_Kategooria ON Toode.toote_kategooria_id = Toote_Kategooria.toote_kategooria_id) INNER JOIN Toote_Kategooria_Klass ON Toote_Kategooria.toote_kategooria_klassi_id = Toote_Kategooria_Klass.toote_kategooria_klassi_id WHERE Toode.toote_id = ?";
module.exports.joogid = "SELECT * FROM (Toode INNER JOIN Toote_Kategooria ON Toode.toote_kategooria_id = Toote_Kategooria.toote_kategooria_id) INNER JOIN Toote_Kategooria_Klass ON Toote_Kategooria.toote_kategooria_klassi_id = Toote_Kategooria_Klass.toote_kategooria_klassi_id WHERE Toote_Kategooria.toote_kategooria_klassi_id = 1 ORDER BY Toode.toote_kategooria_id, Toode.toote_nimetus";
module.exports.soogid = "SELECT * FROM (Toode INNER JOIN Toote_Kategooria ON Toode.toote_kategooria_id = Toote_Kategooria.toote_kategooria_id) INNER JOIN Toote_Kategooria_Klass ON Toote_Kategooria.toote_kategooria_klassi_id = Toote_Kategooria_Klass.toote_kategooria_klassi_id WHERE Toote_Kategooria.toote_kategooria_klassi_id = 2 ORDER BY Toode.toote_kategooria_id, Toode.toote_nimetus";
module.exports.ostud = "SELECT DATE_FORMAT(aeg, '%d.%m.%Y %H:%i') AS aeg, ostja_nimi, toote_nimi, kogus, summa, on_tasuta, rebane_ostis FROM Ost ORDER BY DATE(aeg) DESC, TIME(aeg) DESC";
module.exports.volad = "SELECT Kasutaja_Staatus.staatuse_nimetus as staatus, eesnimi, perenimi, volg FROM Kasutaja INNER JOIN Kasutaja_Staatus ON Kasutaja.kasutaja_staatuse_id = Kasutaja_Staatus.kasutaja_staatuse_id WHERE volg > 0";
module.exports.nulliVolad = "UPDATE Kasutaja SET volg = 0 WHERE volg <> 0";
module.exports.ostudAEG = "SELECT DATE_FORMAT(aeg, '%d.%m.%Y %H:%i') AS aeg, ostja_nimi, toote_nimi, kogus, summa, summa_oma_hind, on_tasuta, rebane_ostis FROM Ost WHERE aeg BETWEEN ? and ? ORDER BY DATE(aeg) DESC, TIME(aeg) DESC";
module.exports.toodeteMuutused = "SELECT DATE_FORMAT(aeg, '%d.%m.%Y %H:%i') AS aeg, toote_nimi, kogus, tegevus FROM Toote_Koguse_Muutus ORDER BY DATE(aeg) DESC, TIME(aeg) DESC";
module.exports.kasutajateMuutused = "SELECT DATE_FORMAT(aeg, '%d.%m.%Y %H:%i') AS aeg, kasutaja_nimi, tegevus, muudeti FROM Kasutaja_Muutus ORDER BY DATE(aeg) DESC, TIME(aeg) DESC";
module.exports.getToodeID = "SELECT * FROM Toode WHERE toote_id = ?";
module.exports.rebasteJoodudOlled = "SELECT COALESCE(SUM(summa_oma_hind), 0) AS olledSumma FROM Ost WHERE aeg >= (SELECT teostatud FROM Kuu_Lopp ORDER BY teostatud DESC LIMIT 1) AND aeg < CURDATE() AND ostja_nimi LIKE 'reb! %' AND on_tasuta = 1";
module.exports.getTooted = "SELECT toote_kategooria_id, toote_nimetus, myygi_hind, oma_hind, hetke_kogus FROM Toode ORDER BY toote_kategooria_id";
module.exports.insertKuuLopp = "INSERT INTO Kuu_Lopp (rebaste_joogid, volad_kokku) VALUES (?, ?)";
module.exports.getLatestLockState = "SELECT * FROM Luku_Oleku_Muutmine ORDER BY muutuse_aeg DESC LIMIT 1";
module.exports.setLockState = "INSERT INTO Luku_Oleku_Muutmine (lukk_kinni) VALUES (?)";
module.exports.getCredentials = "SELECT kasutaja_nimi, salasona FROM Autentimine WHERE nimetus = ?";